# Generated by Django 4.2.1 on 2023-07-03 16:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OBJECTID', models.IntegerField()),
                ('CODE', models.CharField(max_length=50)),
                ('SCHOOL_NAM', models.CharField(max_length=255)),
                ('LEVEL', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('County', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('ZONE', models.CharField(max_length=50)),
                ('SUBCOUNTY', models.CharField(max_length=50)),
                ('Ward', models.CharField(max_length=50)),
                ('X_Coord', models.FloatField()),
                ('Y_Coord', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
